[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/portals"
  to = "/.netlify/functions/portals"
  status = 200
  force = true

[[redirects]]
  from = "/portal/:slug"
  to = "/.netlify/functions/serve"
  status = 200
  force = true
