[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/portal/:slug"
  to = "/.netlify/functions/serve"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
